import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Cormorant_Unicase } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-outfit',          
})

const cormorantUnicase = Cormorant_Unicase({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-cormorant-unicase',
})

import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Boluwatife Ajibola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${cormorantUnicase.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#0C0C0C]`}
    >
      <body className="min-h-full bg-[#0C0C0C]">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
